# Generated by Django 5.1.7 on 2025-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(blank=True, default='')),
                ('prodapp', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('NF', 'Non-Fiction'), ('F', 'Fiction'), ('LR', 'Love & Romance'), ('T', 'Thriller'), ('SF', 'Science Fiction'), ('AA', 'Action & Adventure'), ('D', 'Drama'), ('C', 'Comedy'), ('P', 'Poetry'), ('CL', 'Classic'), ('YA', 'Young Adult')], max_length=3)),
                ('product_image', models.ImageField(upload_to='books/')),
            ],
        ),
    ]
